### ISSUE TITLE
No MakeDefs.u, DgnComp.u, LevComp.u, and NetHack.u projects for sys/mac?

### ISSUE THREAD

**Issue by karianna** [MaddTheSane/NetHack-Mac-OS-X#4]
Was following Install.mw file under /sys/mac but I don't see the projects mentioned in the first step.

**Comment by MaddTheSane** [comment]
`/sys/mac` are files for the Classic (pre-OS X) versions of Mac OS. The project I use can be found in `/win/cocoa`.

**Comment by karianna** [comment]
@MaddTheSane Ah Thank you - found the XCode project, built it and have an App :-)
